apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::200385471840:role/eksctl-eks-cluster-nodegroup-eks-NodeInstanceRole-135KJ9SSUUNKG
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::200385471840:user/prasanth-roboshop
      username: roboshop-project
kind: ConfigMap
metadata:
  creationTimestamp: "2023-05-28T12:59:12Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1099"
  uid: d27d05e7-b7fd-43fa-a977-e04a7ede891f
